### ISSUE TITLE
deb package unable to locate

### ISSUE THREAD

**Issue by olav2021** [tareksander/termux-gui-package#1]
Hello,

after installing the termux-app-universal apk and pkg install termux-create-package , this is another error:

apt install termux-gui-package_0.1.4_all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package termux-gui-package_0.1.4_all.deb

I might to reinstall termux bootstrap and try again, do I?

**Comment by tareksander** [comment]
It is important to write `./termux-gui-package_0.1.4_all.deb`, if you don't write `./` it searches the Termux repo for the package instead of using the file.

**Comment by zhangjing-GitHub-Code** [comment]
Is that OK?
You need install .deb package by running `dpkg` command.
In this example you should run `dpkg -i termux-gui-package_0.1.4_all.deb`.

**Comment by tareksander** [comment]
termux-gui-package is now included in the repo and can be installed with `pkg install termux-gui-package`.
