### ISSUE TITLE
How to install termux-gui

### ISSUE THREAD

**Issue by olav2021** [tareksander/termux-gui-package#2]
Hello,

I installed a fresh termux from f-droid-app, but the store version of termux:GUI still does not want to install.

Earlier, the over way of installing all from github, was not successful , too.

When comes a f-droid certified version?

**Comment by tareksander** [comment]
The f-droid version currently has signing key issues, preventing it from working with the f-droid version of Termux.  
You can watch [this](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/10240) PR to see the progress of this.  
I don't know if the f-droid people work on f-droid over the holidays, so I don't know how long that will take.

**Comment by tareksander** [comment]
Closing this now as it doesn't relate to termux-gui-package, if you want to see the state of Termux:GUI on f-droid, see this issue: termux/termux-gui#4
