### ISSUE TITLE
Change in installation guide

### ISSUE THREAD

**Issue by Haiz14** [tareksander/termux-gui-package#4]
I tried to install the latest release of the pkg but when I tried to use apt it doesn't work `~/downloads $ apt install ./file.deb.
Reading package lists... Done
E: Unsupported file ./file.deb. given on commandline
~/downloads $ apt install termux-gui-package_0.1.5_all.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package termux-gui-package_0.1.5_all.deb`

But dpkg worked`~/downloads $ dpkg -i termux-gui-package_0.1.5_all.deb
Selecting previously unselected package termux-gui-package.
(Reading database ... 32379 files and directories currently installed.)
Preparing to unpack termux-gui-package_0.1.5_all.deb ...
Unpacking termux-gui-package (0.1.5) ...
Setting up termux-gui-package (0.1.5) ...
Installing python bindings for Termux:GUI
Requirement already satisfied: termuxgui in /data/data/com.termux/files/usr/lib/python3.10/site-packages (0.1.4)
Processing triggers for man (1.14.5-3) ...
~/downloads $ termux-gui-files`

So I thought you should change the apt to dpkg

**Comment by ksyko** [comment]
This works:
```
chmod +x termux-gui-package_0.1.5_all.deb
apt install ./termux-gui-package_0.1.5_all.deb
```

**Comment by tareksander** [comment]
termx-gui-package is now included in the repo and can be installed with `pkg install termux-gui-package`
