### ISSUE TITLE
dmenu like menu

### ISSUE THREAD

**Issue by odnar-dev** [tareksander/termux-gui-package#7]
reads arbitrary text from stdin, and creates a menu with one item for each line. The user can then select an item and the line is printed to stdout.

https://tools.suckless.org/dmenu/

**Comment by tareksander** [comment]
You can do something similar with termux-gui-dialog and a spinner:

![](https://user-images.githubusercontent.com/57038324/158857479-ee64909e-faf3-489d-82a5-66725fda2065.png)

There is just 2 additional clicks: One to open up the spinner and one to click "Submit".

**Comment by odnar-dev** [comment]
i like the menu in `termux-gui-pkg`, and i think maybe that is a better interface
- provide search bar (
- option to select multiple items

if we modified that to read data from stdin, and printed selected items to stdout.
it can be a drop in replacement for dmenu

**Comment by tareksander** [comment]
I implemented this by the way, forgot to mention it. Will be included in the next release.
![dmenu](https://user-images.githubusercontent.com/57038324/191949541-f8e398b7-0b04-4452-8eb3-7be73f8ea307.png)
The input filters the displayed buttons, and the text of a button is output to stdout on click. I don't use dmenu myself, so I don't know what other features it has.
